### ISSUE TITLE
Adding elm/url dependency breaks the project

### ISSUE THREAD

**Issue by kirillt** [avh4/elm-desktop-app#3]
Hi! I only started to investigate Elm and probably I do something wrong.
But it feels that this way should work.
```
[kirill@centos7]$ mkdir test
[kirill@centos7]$ cd test
[kirill@centos7 test]$ elm-desktop-app init
[kirill@centos7 test]$ elm-desktop-app run   # requires ownership by root and 4755 privileges
[kirill@centos7 test]$ sudo chown root elm-stuff/elm-desktop-app/app/node_modules/electron/dist/chrome-sandbox 
[kirill@centos7 test]$ sudo chmod 4755 elm-stuff/elm-desktop-app/app/node_modules/electron/dist/chrome-sandbox 
[kirill@centos7 test]$ elm-desktop-app run
Success! Compiled 5 modules.
```
So far so good.
```
[kirill@centos7 test]$ elm install elm/url
[kirill@centos7 test]$ elm-desktop-app run
/home/kirill/test/elm-stuff/elm-desktop-app/app /home/kirill/test
/home/kirill/test
data should have required property 'elm-desktop-app'
```
This error message confuses me. Can I use `elm/url` with `elm-desktop-app`?

**Comment by avh4** [comment]
ah, `elm install` removes things from the elm.json file that it doesn't recognize, so for now I recommend either using elm-json (https://github.com/zwilias/elm-json#readme) to install things (with `elm-json install` instead of `elm install`),  or making sure you have elm.json in version control and putting back the elm-program-test stuff after `elm install` removed it.

**Comment by kirillt** [comment]
@avh4 Thanks! `elm-json` solved my problem.
Great repo.
